/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : PostgreSQL
 Source Server Version : 130002
 Source Host           : localhost:5432
 Source Catalog        : spring_mvc
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 130002
 File Encoding         : 65001

 Date: 23/03/2021 14:20:11
*/


-- ----------------------------
-- Sequence structure for genre_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."genre_id_seq";
CREATE SEQUENCE "public"."genre_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for keywords_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."keywords_id_seq";
CREATE SEQUENCE "public"."keywords_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for movies_genres_movie_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."movies_genres_movie_id_seq";
CREATE SEQUENCE "public"."movies_genres_movie_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for movies_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."movies_id_seq";
CREATE SEQUENCE "public"."movies_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for movies_keywords_movie_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."movies_keywords_movie_id_seq";
CREATE SEQUENCE "public"."movies_keywords_movie_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for ratings_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."ratings_id_seq";
CREATE SEQUENCE "public"."ratings_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for reviewers_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."reviewers_id_seq";
CREATE SEQUENCE "public"."reviewers_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for roles_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."roles_id_seq";
CREATE SEQUENCE "public"."roles_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for users_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."users_id_seq";
CREATE SEQUENCE "public"."users_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
CACHE 1;

-- ----------------------------
-- Table structure for genres
-- ----------------------------
DROP TABLE IF EXISTS "public"."genres";
CREATE TABLE "public"."genres" (
  "id" int4 NOT NULL DEFAULT nextval('genre_id_seq'::regclass),
  "name" varchar COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Table structure for keywords
-- ----------------------------
DROP TABLE IF EXISTS "public"."keywords";
CREATE TABLE "public"."keywords" (
  "id" int4 NOT NULL DEFAULT nextval('keywords_id_seq'::regclass),
  "name" varchar COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Table structure for movies
-- ----------------------------
DROP TABLE IF EXISTS "public"."movies";
CREATE TABLE "public"."movies" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "title" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "description" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "released_date" date NOT NULL,
  "trailer" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "runtime" int2 NOT NULL,
  "number_votes" int8 DEFAULT 0,
  "thumbnail" varchar(255) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Table structure for movies_genres
-- ----------------------------
DROP TABLE IF EXISTS "public"."movies_genres";
CREATE TABLE "public"."movies_genres" (
  "movie_id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "genre_id" int4 NOT NULL
)
;

-- ----------------------------
-- Table structure for movies_keywords
-- ----------------------------
DROP TABLE IF EXISTS "public"."movies_keywords";
CREATE TABLE "public"."movies_keywords" (
  "movie_id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "keyword_id" int4 NOT NULL
)
;

-- ----------------------------
-- Table structure for ratings
-- ----------------------------
DROP TABLE IF EXISTS "public"."ratings";
CREATE TABLE "public"."ratings" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "movie_id" int4 NOT NULL,
  "reviewer_id" int4 NOT NULL,
  "rate" int2 NOT NULL
)
;

-- ----------------------------
-- Table structure for reviewers
-- ----------------------------
DROP TABLE IF EXISTS "public"."reviewers";
CREATE TABLE "public"."reviewers" (
  "id" int4 NOT NULL GENERATED ALWAYS AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "username" varchar(255) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS "public"."roles";
CREATE TABLE "public"."roles" (
  "id" int2 NOT NULL DEFAULT nextval('roles_id_seq'::regclass),
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS "public"."users";
CREATE TABLE "public"."users" (
  "id" int2 NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  "username" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "email" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "password" varchar(255) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Table structure for users_roles
-- ----------------------------
DROP TABLE IF EXISTS "public"."users_roles";
CREATE TABLE "public"."users_roles" (
  "user_id" int4 NOT NULL,
  "role_id" int4
)
;

-- ----------------------------
-- Table structure for watchlists
-- ----------------------------
DROP TABLE IF EXISTS "public"."watchlists";
CREATE TABLE "public"."watchlists" (
  "movie_id" int4 NOT NULL,
  "user_id" int4 NOT NULL
)
;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."genre_id_seq"
OWNED BY "public"."genres"."id";
SELECT setval('"public"."genre_id_seq"', 2, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."keywords_id_seq"
OWNED BY "public"."keywords"."id";
SELECT setval('"public"."keywords_id_seq"', 2, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."movies_genres_movie_id_seq"
OWNED BY "public"."movies_genres"."movie_id";
SELECT setval('"public"."movies_genres_movie_id_seq"', 2, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."movies_id_seq"
OWNED BY "public"."movies"."id";
SELECT setval('"public"."movies_id_seq"', 3, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."movies_keywords_movie_id_seq"
OWNED BY "public"."movies_keywords"."movie_id";
SELECT setval('"public"."movies_keywords_movie_id_seq"', 2, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."ratings_id_seq"
OWNED BY "public"."ratings"."id";
SELECT setval('"public"."ratings_id_seq"', 14, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."reviewers_id_seq"
OWNED BY "public"."reviewers"."id";
SELECT setval('"public"."reviewers_id_seq"', 4, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."roles_id_seq"
OWNED BY "public"."roles"."id";
SELECT setval('"public"."roles_id_seq"', 2, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."users_id_seq"
OWNED BY "public"."users"."id";
SELECT setval('"public"."users_id_seq"', 2, false);

-- ----------------------------
-- Primary Key structure for table genres
-- ----------------------------
ALTER TABLE "public"."genres" ADD CONSTRAINT "genre_pk" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table keywords
-- ----------------------------
ALTER TABLE "public"."keywords" ADD CONSTRAINT "keywords_pk" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table movies
-- ----------------------------
ALTER TABLE "public"."movies" ADD CONSTRAINT "movies_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Uniques structure for table movies_genres
-- ----------------------------
ALTER TABLE "public"."movies_genres" ADD CONSTRAINT "movie_genre" UNIQUE ("movie_id", "genre_id");

-- ----------------------------
-- Uniques structure for table ratings
-- ----------------------------
ALTER TABLE "public"."ratings" ADD CONSTRAINT "movie_reviewer_fk" UNIQUE ("movie_id", "reviewer_id");

-- ----------------------------
-- Primary Key structure for table ratings
-- ----------------------------
ALTER TABLE "public"."ratings" ADD CONSTRAINT "ratings_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table reviewers
-- ----------------------------
ALTER TABLE "public"."reviewers" ADD CONSTRAINT "reviewer_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table roles
-- ----------------------------
ALTER TABLE "public"."roles" ADD CONSTRAINT "roles_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table users
-- ----------------------------
ALTER TABLE "public"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table users_roles
-- ----------------------------
ALTER TABLE "public"."users_roles" ADD CONSTRAINT "users_roles_pkey" PRIMARY KEY ("user_id");

-- ----------------------------
-- Uniques structure for table watchlists
-- ----------------------------
ALTER TABLE "public"."watchlists" ADD CONSTRAINT "movie_user_uq" UNIQUE ("movie_id", "user_id");

-- ----------------------------
-- Foreign Keys structure for table movies_genres
-- ----------------------------
ALTER TABLE "public"."movies_genres" ADD CONSTRAINT "genre_fk" FOREIGN KEY ("genre_id") REFERENCES "public"."genres" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."movies_genres" ADD CONSTRAINT "movie_fk" FOREIGN KEY ("movie_id") REFERENCES "public"."movies" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table movies_keywords
-- ----------------------------
ALTER TABLE "public"."movies_keywords" ADD CONSTRAINT "keyword_fk" FOREIGN KEY ("keyword_id") REFERENCES "public"."keywords" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."movies_keywords" ADD CONSTRAINT "movie_fk" FOREIGN KEY ("movie_id") REFERENCES "public"."movies" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table ratings
-- ----------------------------
ALTER TABLE "public"."ratings" ADD CONSTRAINT "movie_fk" FOREIGN KEY ("movie_id") REFERENCES "public"."movies" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."ratings" ADD CONSTRAINT "reviewer_fk" FOREIGN KEY ("reviewer_id") REFERENCES "public"."reviewers" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table users_roles
-- ----------------------------
ALTER TABLE "public"."users_roles" ADD CONSTRAINT "role_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."users_roles" ADD CONSTRAINT "user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table watchlists
-- ----------------------------
ALTER TABLE "public"."watchlists" ADD CONSTRAINT "movie_fk" FOREIGN KEY ("movie_id") REFERENCES "public"."movies" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."watchlists" ADD CONSTRAINT "user_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
